### ISSUE TITLE
Class 'Media\Classes\MediaLibrary' not found - error when post has an image

### ISSUE THREAD

**Issue by rosolovsky** [Dynamedia/oc-posts-plugin#1]
Class 'Media\Classes\MediaLibrary' not found
in 
plugins/dynamedia/posts/classes/seo/PostSeoParser.php line 79

` if ($imageUrl) {
            $image = SchemaFactory::makeSpatie('imageObject')
                ->url(\URL::to(\Media\Classes\MediaLibrary::url($imageUrl)));
            $article->image($image);
        }`

**Comment by robballantyne** [comment]
Thanks I'll try and replicate tonight.

Can you confirm October CMS version please?

**Comment by rosolovsky** [comment]
October CMS version 1.1.9 with Laravel 6.20.41

**Comment by robballantyne** [comment]
Unfortunately it's an issue with October v1 compatibility.

I chose not to support versions prior to v2 because changes to the marketplace would require an October license in order to purchase Posts Commercial License. Honestly, I think moving to v2 for greenfield projects makes sense despite the cost. Marketplace T&C's mean I couldn't sell the license outside of the marketplace so it would be a lot of extra work to maintain.

However, I do have a version which supports Winter CMs (the community fork of Octover v1) which does still require a Posts license but the base CMS remains free.

Hope this helps but sorry I can't fix for v1.
